server {
    listen __EDEX_WEB_PORT__ ssl;
    server_name _;

    ssl_certificate __EDEX_SSL_CERT__;
    ssl_certificate_key __EDEX_SSL_KEY__;

    auth_basic "eDEX-UI";
    auth_basic_user_file __EDEX_HTPASSWD_FILE__;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_buffering off;

    location / {
        proxy_pass http://__EDEX_NOVNC_HOST__:__EDEX_NOVNC_PORT__/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /websockify {
        proxy_pass http://__EDEX_NOVNC_HOST__:__EDEX_NOVNC_PORT__/websockify;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /websockify/ {
        proxy_pass http://__EDEX_NOVNC_HOST__:__EDEX_NOVNC_PORT__/websockify/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
